// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Lighting","status":true,"description":"v2.6 Creates an extra layer that darkens a map and adds lightsources! Released under the MIT license!","parameters":{"---General Settings---":"","Options Menu Entry":"Lighting Effects","Light event required":"false","Reset Lights":"false","Kill Switch":"D","Kill Switch Auto":"true","Note Tag Key":"cl","---DayNight Settings---":"","Save DaynightHours":"2","Save DaynightMinutes":"3","Save DaynightSeconds":"4","Save Night Switch":"1","Night Hours":"0, 1, 2, 3, 4, 5, 6, 19, 20, 21, 22, 23","DayNight Colors":"[\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#9999ff\",\"#ccccff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffcc88\",\"#9999ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\"]","---Offset and Sizes---":"","Lights Active Radius":"20","Player radius":"0","Flashlight offset":"0","Screensize X":"866","Screensize Y":"675","Lightmask Padding":"40","---Battle Settings---":"","Battle Tinting":"true","Light Mask Position":"Between"}}
];
